name: "🐛 Bug"
description: "Something is broken"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        What's broken? Let's fix it.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How bad is it?
      options:
        - "🔥 Critical - Production down, data loss, security issue"
        - "🟠 High - Major feature broken, no workaround"
        - "🟡 Medium - Feature broken but has workaround"
        - "🟢 Low - Minor issue, cosmetic, edge case"
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: What's broken?
      description: One sentence description
      placeholder: "Login button doesn't work on mobile Safari"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen?
      placeholder: "Clicking login should open the auth modal"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happens?
      placeholder: "Nothing happens. Console shows: TypeError..."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: Steps to trigger the bug
      placeholder: |
        1. Open site on iPhone Safari
        2. Tap Login button
        3. Nothing happens
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Environment / Context
      description: Browser, OS, device, account type, etc.
      placeholder: "iOS 17, Safari, iPhone 15 Pro"
    validations:
      required: false
