name: "🎯 Task"
description: "Standard work item - features, changes, improvements"
title: "[TASK] "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        ## Quick Task Creation
        Keep it simple. One task = one thing to do.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this?
      options:
        - "P0 - Do it now (blocks everything)"
        - "P1 - Today"
        - "P2 - This week"
        - "P3 - Backlog"
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: What needs to happen?
      description: One sentence. If it's more than one sentence, split into multiple issues.
      placeholder: "Add a logout button to the nav bar"
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: Definition of done
      description: How do we know this is complete?
      placeholder: |
        - Logout button visible in nav
        - Clicking it clears session and redirects to /login
        - Works on mobile
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: Any additional info that helps
      placeholder: "Related to issue #45. See Figma design at..."
    validations:
      required: false

  - type: dropdown
    id: assignee
    attributes:
      label: Who should handle this?
      description: Human or agent?
      options:
        - "Codex / Agent"
        - "Human (me)"
        - "Unassigned - triage needed"
    validations:
      required: false
